<?php

function jamies_follow_custom_follow_networks_alter(&$networks, $uid = 0) {
  // Add a network.
  $networks[$uid]['imdb'] = array (
    'title' => t('IMDB'),
    'domain' => 'imdb.com',
  );

  $networks[$uid]['drupal'] = array (
    'title' => t('drupal.org'),
    'domain' => 'drupal.org',
  );

  $networks[$uid]['etsy'] = array (
    'title' => t('Etsy.com'),
    'domain' => 'etsy.com',
  );

  $networks[$uid]['redbubble'] = array (
    'title' => t('Redbubble.com'),
    'domain' => 'redbubble.com',
  );

  //We set the path below to the custom css
  drupal_add_css(drupal_get_path('module', 'jamies_follow') .'/css/custom.css',
  array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}
