<?php
/**
 * @file
 * custom_content_.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function custom_content__field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-awards_and_reviews-field_awards_and_reviews_list'.
  $field_instances['node-awards_and_reviews-field_awards_and_reviews_list'] = array(
    'bundle' => 'awards_and_reviews',
    'default_value' => array(
      0 => array(
        'value' => 'Use a single lines to describe your awards.

It\'ll keep things clear.

Just like I have here.',
      ),
    ),
    'deleted' => 0,
    'description' => 'Use a sentence or two to describe your award or review.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_awards_and_reviews_list',
    'label' => 'Awards and reviews list',
    'required' => 1,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-awards_and_reviews-field_picture'.
  $field_instances['node-awards_and_reviews-field_picture'] = array(
    'bundle' => 'awards_and_reviews',
    'deleted' => 0,
    'description' => 'Upload an picture here. Make sure it isn\'t sideways or upside down. Use a creative description for the "alt" field. ',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_picture',
    'label' => 'picture',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '10 MB',
      'max_resolution' => '900x900',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-news_blog-body'.
  $field_instances['node-news_blog-body'] = array(
    'bundle' => 'news_blog',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'What would you like to share with the world?',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'News and Thoughts',
    'required' => 1,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 15,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => -4,
    ),
  );

  // Exported field_instance: 'node-news_blog-field_pictures'.
  $field_instances['node-news_blog-field_pictures'] = array(
    'bundle' => 'news_blog',
    'deleted' => 0,
    'description' => 'Upload pictures of interest.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_pictures',
    'label' => 'Pictures',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '10 MB',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => -3,
    ),
  );

  // Exported field_instance: 'node-tips_and_tricks-body'.
  $field_instances['node-tips_and_tricks-body'] = array(
    'bundle' => 'tips_and_tricks',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'List out your tips and tricks!',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Tips and tricks',
    'required' => 1,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 10,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => -4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Awards and reviews list');
  t('List out your tips and tricks!');
  t('News and Thoughts');
  t('Pictures');
  t('Tips and tricks');
  t('Upload an picture here. Make sure it isn\'t sideways or upside down. Use a creative description for the "alt" field. ');
  t('Upload pictures of interest.');
  t('Use a sentence or two to describe your award or review.');
  t('What would you like to share with the world?');
  t('picture');

  return $field_instances;
}
