<?php
function firstajax_menu() {
  $items['path-to-ajax/%/%'] = array(
          'access to arguments' => array('access content'),
          'page callback' => 'firstajax_ajax_callback',
          'page arguments' => array(1,2),
          'type' => MENU_CALLBACK,
  );
  return $items;
}

function firstajax_ajax_callback($js, $node_id) {
  $node = node_load($node_id);

  if ($js == 'nojs') {
    drupal_goto('node/' .$node->nid);
  }

  // Get the render array for the node, and render it into atual HTML
  $build = node_view($node);
  $html = render($build);

  // Here we prepare an ajax command to insert the node's HTML into our div under News -the wrapper.
  $commands = array();
  $commands[] ajax_command_html('#firstajax-ajax-wrapper', $html);

  // Render the commands int JSON data format and execute them by printing them to the browser.
  print ajax_render($commands);
  exit; //Exit so Drupal doesn't have a chance to build a whole page.
}
